### ISSUE TITLE
Add check for coinbase maturity for transparent outputs

### ISSUE THREAD

**Issue by dimxy** [KomodoPlatform/zebra#11]
Currently the original zcash/zebra restriction to spend coinbases to transparent outputs is just disabled to allow syncing to komodod nodes.
We need to add code to check coinbase maturity (for SomeTransparentOutputs case)

**Comment by DeckerSU** [comment]
Implemented in https://github.com/KomodoPlatform/zebra/tree/patch-coinbase-maturity, also covered by unit tests. 

Under tests now: full-sync, etc. When tests will be finished - will create PR in `main`.
