### ISSUE TITLE
implement komodo_check_deposit rules

### ISSUE THREAD

**Issue by dimxy** [KomodoPlatform/zebra#19]
implement the komodo_check_deposit function rules in its part for kmd

**Comment by DeckerSU** [comment]
`komodo_check_deposit` consists of the following checks for KMD:
- [x] vins of each tx shouldn't be banned (already implemented in `tx_has_banned_inputs`.
- [ ] last transaction in a block in case of block is notary mined, should satisfy certain conditions, like first vout = 5000, `scriptPubKey` of coinbase tx must equal to `scriptPubKey` of `notaryvin` (last tx vin).
- [ ] validate strangeouts (coinbase vouts)

**Comment by DeckerSU** [comment]
Almost done in this branch - [patch-komodo-check-deposit](https://github.com/KomodoPlatform/zebra/tree/patch-komodo-check-deposit), need to fix broken tests and polish / clean the code alongside with sync tests.
