### ISSUE TITLE
Remove mempool transactions spending coinbases that become immature due to reorg

### ISSUE THREAD

**Issue by dimxy** [KomodoPlatform/zebra#27]
Implement removal of mempool transactions spending coinbases which become immature due to a chain reorganisation.
This is equal to komodod removeForReorg() function.

**Comment by DeckerSU** [comment]
I may be wrong, but it looks like in the case of [`TipAction::Reset`](https://github.com/KomodoPlatform/zebra/blob/main/zebra-state/src/service/chain_tip.rs#L433), when the best chain is switched (rollback/reorg), skipped blocks, or activated network upgrade, the mempool is [cleared anyway](https://github.com/KomodoPlatform/zebra/blob/main/zebrad/src/components/mempool.rs#L308). 

If the mempool has transactions that spend coinbase transactions that no longer exist in the main (best) chain, then after switching to a different best chain the mempool should be cleared.

So, seems we don't need additional removal. Correct me plz, if I'm wrong.

**Comment by dimxy** [comment]
yes you are right, now I can see this myself - zebra removes all mempool state in case of a reorg (tip reset)
closing this issue
